version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment: 
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432" 
  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.18
    ports:
    - "5775:5775"
    - "6831:6831"
    - "6832:6832"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "14250:14250"
    - "9411:9411"